service: posts

provider:
  name: aws
  runtime: python3.7
  memorySize: 128

package:
  exclude:
    - test.py

functions:
  listPosts:
    handler: handler.list_posts
    events:
      - http:
          path: posts
          method: get

  getPost:
    handler: handler.get_post
    events:
      - http:
          path: posts/{id}
          method: get

plugins:
  - serverless-python-requirements
